# Metode Gauss Jordan

In [ ]:
import numpy as np
n = m = 5
a = [[8,2,-4,6,-1],[3,-1,4,-6,7],[-9,1,-1,-1,2],[1,-1,1,-1,1],[3,4,-2,4,8]]
b = [418,-216,-178,-28,218]
c = np.zeros([m,n+1])


for i in range(m):
  for j in range(n):
    c[i][j] = a[i][j]
for i in range(m):
  c[i][n] = b[i]
print(c)
for k in range(m):
  p = c[k][k]
  for j in range(k,n+1):
    c[k][j] = c[k][j]/p
  for i in range(k+1,m):
    p = c[i][k]
    for j in range(k,n+1):
      c[i][j] = c[i][j] - c[k][j]*p

for k in range(m-1,-1,-1):
  for i in range(k-1,-1,-1):
    p = c[i][k]
    for j in range(k,n+1):
      c[i][j] = c[i][j]-c[k][j]*p

for i in range(0,m):
  print("x{:d} = {:.2f}".format(i+1,c[i][-1]))


[[   8.    2.   -4.    6.   -1.  418.]
 [   3.   -1.    4.   -6.    7. -216.]
 [  -9.    1.   -1.   -1.    2. -178.]
 [   1.   -1.    1.   -1.    1.  -28.]
 [   3.    4.   -2.    4.    8.  218.]]
x1 = 18.00
x2 = -8.00
x3 = -22.00
x4 = 34.00
x5 = 2.00


# Numpy

In [ ]:
# penyelesaian dengan numpy
print(np.linalg.solve(a,b))

[ 18.  -8. -22.  34.   2.]



# Metode LU

In [ ]:
def lu_manual(A):
    A = A.astype(float)
    n = A.shape[0]

    U = A.copy()
    L = np.eye(n, dtype=np.double)

    for i in range(n):

        factor = U[i+1:, i] / U[i, i]
        L[i+1:, i] = factor
        U[i+1:] -= factor[:, np.newaxis] * U[i]

    return L, U

def forward_substitution(L, b):

    n = L.shape[0]

    y = np.zeros_like(b, dtype=np.double);

    y[0] = b[0] / L[0, 0]


    for i in range(1, n):
        y[i] = (b[i] - np.dot(L[i,:i], y[:i])) / L[i,i]

    return y

def back_substitution(U, y):

    n = U.shape[0]
    x = np.zeros_like(y, dtype=np.double);
    x[-1] = y[-1] / U[-1, -1]
    for i in range(n-2, -1, -1):
        x[i] = (y[i] - np.dot(U[i,i:], x[i:])) / U[i,i]

    return x

In [ ]:
a = np.array([[8,2,-4,6,-1],[3,-1,4,-6,7],[-9,1,-1,-1,2],[1,-1,1,-1,1],[3,4,-2,4,8]])
b = np.array([418,-216,-178,-28,218])
## %inisialisasi matriks A dan B
A = a.copy()
B = b.copy()

Lm,Um = lu_manual(A)
print("L:\n",Lm)
print("U:\n",Um)
print("LU=A:\n",np.dot(Lm,Um))
print("---")
ym = forward_substitution(Lm,B)
xm = back_substitution(Um,ym)
print(xm)

L:
 [[ 1.          0.          0.          0.          0.        ]
 [ 0.375       1.          0.          0.          0.        ]
 [-1.125      -1.85714286  1.          0.          0.        ]
 [ 0.125       0.71428571 -0.51515152  1.          0.        ]
 [ 0.375      -1.85714286  2.06060606 -7.80769231  1.        ]]
U:
 [[ 8.          2.         -4.          6.         -1.        ]
 [ 0.         -1.75        5.5        -8.25        7.375     ]
 [ 0.          0.          4.71428571 -9.57142857 14.57142857]
 [ 0.          0.          0.         -0.78787879  3.36363636]
 [ 0.          0.          0.          0.         18.30769231]]
LU=A:
 [[ 8.  2. -4.  6. -1.]
 [ 3. -1.  4. -6.  7.]
 [-9.  1. -1. -1.  2.]
 [ 1. -1.  1. -1.  1.]
 [ 3.  4. -2.  4.  8.]]
---
[ 18.  -8. -22.  34.   2.]


# Scipy

In [ ]:
# LU Decomposition dengan scipy
A = np.array([[8,2,-4,6,-1],[3,-1,4,-6,7],[-9,1,-1,-1,2],[1,-1,1,-1,1],[3,4,-2,4,8]])
B = np.array([418,-216,-178,-28,218])

from scipy.linalg import lu
P, L, U, = lu(A)
print("P:\n",P)
print("L:\n",L)
print("U:\n",U)
print("LU:\n",np.dot(L,U))
print("-------")

y = forward_substitution(L,np.dot(P,B))
x = back_substitution(U,y)
print(x)

P:
 [[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]
L:
 [[ 1.          0.          0.          0.          0.        ]
 [-0.33333333  1.          0.          0.          0.        ]
 [-0.88888889  0.66666667  1.          0.          0.        ]
 [-0.33333333 -0.15384615 -0.99230769  1.          0.        ]
 [-0.11111111 -0.20512821 -0.12307692  0.00985222  1.        ]]
U:
 [[-9.          1.         -1.         -1.          2.        ]
 [ 0.          4.33333333 -2.33333333  3.66666667  8.66666667]
 [ 0.          0.         -3.33333333  2.66666667 -5.        ]
 [ 0.          0.          0.         -3.12307692  4.03846154]
 [ 0.          0.          0.          0.          2.34482759]]
LU:
 [[-9.  1. -1. -1.  2.]
 [ 3.  4. -2.  4.  8.]
 [ 8.  2. -4.  6. -1.]
 [ 3. -1.  4. -6.  7.]
 [ 1. -1.  1. -1.  1.]]
-------
[  81.30252101  302.29411765 -169.93697479 -268.36554622  -93.43697479]


# Aplikasi pada HK Kirchoff

In [ ]:
import numpy as np
m = 3 # Jumlah baris matriks
n = 3 # Jumlah kolom matriks
a = [[30,-12,0],[30,0,9],[1,1,-1]] # Matriks Hk Kirchoof
b = [36,12,0]
c = np.zeros([m,n+1])
for i in range(m):
    for j in range(n):
        c[i][j] = a[i][j]
for i in range(m):
    c[i][n] = b[i]

print("Persamaan Matrik")
print(c)
print()
# -- Proses Eliminasi --
for k in range(m):
    p = c[k][k]
    for j in range(k,n+1):
        c[k][j] = c[k][j]/p

    for i in range(k+1,m):
        p = c[i][k]
        for j in range(k,n+1):
            c[i][j] = c[i][j] - c[k][j]*p
for k in range(m-1,-1,-1):
    for i in range(k-1,-1,-1):
        p = c[i][k]
        for j in range(k,n+1):
            c[i][j] = c[i][j] - c[k][j]*p
print("Hasil dari Gauss Jordan")
print(c)
print()
# Menampilkan nilai I1,I2 dan I3
print("Hasil dari I1,I2, dan I3")
for i in range(0,m):
    print("I{:d} = {:.3f}".format(i+1,c[i][m]))

Persamaan Matrik
[[ 30. -12.   0.  36.]
 [ 30.   0.   9.  12.]
 [  1.   1.  -1.   0.]]

Hasil dari Gauss Jordan
[[ 1.          0.          0.          0.63414634]
 [ 0.          1.          0.         -1.41463415]
 [ 0.          0.          1.         -0.7804878 ]]

Hasil dari I1,I2, dan I3
I1 = 0.634
I2 = -1.415
I3 = -0.780
